disabled_rules:
- trailing_whitespace
- force_cast
- force_try
- file_length
- weak_delegate
- class_delegate_protocol
- nesting
excluded:
- SwiftLint/Common/3rdPartyLib
- Pods/
- vendor/
line_length:
    warning: 150
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 12
type_body_length:
    warning: 300
    error: 700
cyclomatic_complexity:
    warning: 15
    error: 25
identifier_name:
  min_length:
    warning: 3
  excluded: 
      - id
      - to
      - apiError(error:)
reporter: "xcode"
