# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
    
  desc "Run Tests"
  lane :tests do
    scan(scheme: "IngresseSDK",
      code_coverage: true,
      derived_data_path: "DerivedData")
    slather(build_directory: "DerivedData",
      scheme: "IngresseSDK",
      proj: "IngresseSDK.xcodeproj",
      circleci: true,
      coveralls: true,
      simple_output: true)
  end
end
    