name: Deploy Release
on:
  release:
    types: [published]
jobs:
  check:
    name: Deploy
    runs-on: macOS-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
      RELEASE_TAG: ${{ toJson(github.event.release.tag_name) }}
    steps:
    - uses: actions/checkout@v1
    - name: See github trigger
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Update fastlane
      run: sudo gem install fastlane
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Fastlane test
      run: fastlane test
    - name: Publish SDK to Cocoapods
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
    - name: Notify on slack
      run: fastlane notify_slack