name: Deploy Release
on:
  release:
    types: [published]
jobs:
  check:
    name: Deploy
    runs-on: macOS-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
      RELEASE_TAG: ${{ toJson(github.event.release.tag_name) }}
    steps:
    - uses: actions/checkout@v1
    - name: See github trigger
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    # Bundler
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --full-index

    # Cocoapods
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install pods
      run: bundle exec pod install

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Fastlane test
      run: bundle exec fastlane test

    - name: Publish SDK to Cocoapods
      run: |
        set -eo pipefail
        bundle exec pod lib lint --allow-warnings
        bundle exec pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

    - name: Notify on slack
      run: bundle exec fastlane notify_slack