name: Deploy Release
on:
  release:
    types: [published, edited]
jobs:
  check:
    name: Deploy
    runs-on: macOS-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    - name: See github trigger
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Update fastlane
      run: sudo gem install fastlane
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Fastlane test
      run: fastlane test
    - name: Publish SDK to Cocoapods
      env:
        RELEASE_TAG: ${{ toJson(github.event.release.tag_name) }}
      run: fastlane push_to_cocoapods version:$RELEASE_TAG