name: Regular branch
on: [pull_request]
jobs:
  test:
    name: Test Job
    runs-on: macOS-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    - name: Install project dependencies
      run: bundle install
    - name: Install Pods
      run: bundle exec pod install
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Fastlane test
      run: bundle exec fastlane test
