name: Regular branch
on: [push]
jobs:
  test:
    name: Test Job
    runs-on: macOS-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Fastlane test
      run: fastlane tests
